### ISSUE TITLE
DeepOLA: Experiment Tracker

### ISSUE THREAD

**Issue by nikhil96sher** [illinoisdata/DeepOLA#136]
## Overall Status

| Method   | Experiment Scripts | Scale = 1 Test Results | Scale = 10 Run | Scale = 100 Run |
|----------|--------------------|------------------------|----------------|-----------------|
| WAKE     | 
| Presto   |                    |                        |                |                 |
| Polars |                    |                        |                |                 |
| Postgres |                    |                        |                |                 |
| ProgressiveDB |                    |                        |                |                 |
| WanderJoin |                    |                        |                |                 |

## Experiment Setup
- [ ] Azure VM
- [ ] Data Generation
- Things to Remember
  - Important: Disable Cache
  - Scale (1,10,100) and partitions (10, 100, 1000) values might change. 

## WAKE
- [ ] Implementation: 22 Queries Without Scaling
- [ ] Implementation: 22 Queries With Scaling 
- [ ] Script to set up the repository and run experiments
- [ ] Latency Results
  - [ ] Scale = 1; Partition = 10 dataset.
  - [ ] Scale = 10; Partition = 100 dataset.
  - [ ] Scale = 100; Partition = 1000 dataset.
- [ ] Error Results
  - [ ] Scale = 1; Partition = 10 dataset.
  - [ ] Scale = 10; Partition = 100 dataset.
  - [ ] Scale = 100; Partition = 1000 dataset.
- [ ] Variation of Partitions Experiment
- [ ] Variation of Scaling Methods Experiment

## Presto
- [ ] Experiment Script
- [ ] Latency Results on Scale = 1; No partitions dataset.
- [ ] Latency Results on Scale = 10; No partitions dataset.
- [ ] Latency Results on Scale = 100; No partitions dataset.

## Polars
- [ ] Experiment Script
- [ ] Latency Results on Scale = 1; No partitions dataset.
- [ ] Latency Results on Scale = 10; No partitions dataset.
- [ ] Latency Results on Scale = 100; No partitions dataset.

## Postgres
- [ ] Experiment Script
- [ ] Latency Results on Scale = 1; No partitions dataset.
- [ ] Latency Results on Scale = 10; No partitions dataset.
- [ ] Latency Results on Scale = 100; No partitions dataset.

## ProgressiveDB
- [ ] Experiment Script
- [ ] Latency
  - [ ] Scale = 1; Partition = 10 dataset
  - [ ] Scale = 10; Partition = 100 dataset
  - [ ] Scale = 100; Partition = 1000 dataset
- [ ] Error
  - [ ] Scale = 1; Partition = 10 dataset
  - [ ] Scale = 10; Partition = 100 dataset
  - [ ] Scale = 100; Partition = 1000 dataset

## WanderJoin
- [ ] Experiment Script
- [ ] Latency
  - [ ] Scale = 1; Partition = 10 dataset
  - [ ] Scale = 10; Partition = 100 dataset
  - [ ] Scale = 100; Partition = 1000 dataset
- [ ] Error
  - [ ] Scale = 1; Partition = 10 dataset
  - [ ] Scale = 10; Partition = 100 dataset
  - [ ] Scale = 100; Partition = 1000 dataset

**Comment by pyongjoo** [comment]
@mIXs222 Please leave a comment here if you finish adding placeholder figures. Overleaf link: https://www.overleaf.com/project/6213dd85e75ce371a781fed9
