### ISSUE TITLE
TPC-H Queries in DeepOLA Tracker

### ISSUE THREAD

**Issue by nikhil96sher** [illinoisdata/DeepOLA#60]
**TPC-H Queries**
- [x] Q1
- [x] Q2: Aggregate result as part of predicate.
- [x] Q3
- [x] Q4: Exists keyword.
- [x] Q5: Deciding JOIN order.
- [x] Q6
- [x] Q7: Table used twice + Derived function on date.
- [x] Q8: Table used twice + Derived function on date.
- [x] Q9: Deciding JOIN order.
- [x] Q10
- [x] Q11: Having keyword.
- [x] Q12
- [x] Q13: Left Outer JOIN.
- [x] Q14
- [x] Q15: Create VIEW.
- [x] Q16: COUNT DISTINCT + NOT IN keyword.
- [x] Q17: Aggregate result as part of predicate.
- [x] Q18: IN + HAVING keyword.
- [x] Q19
- [x] Q20: Doubly nested IN.
- [x] Q21: Exists + NOT Exists.
- [x] Q22: Aggregate result as part of predicate + not exists.
